version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker_app_db
      MYSQL_USER: luannv
      MYSQL_PASSWORD: 123
      TZ: UTC
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: tracker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
